export const STROKE_DASH_OFFSET = 56.3467

export const STROKE_SUCCESS_COLOR = '#1D9BF0'

export const STROKE_WARNING_COLOR = '#FFD400'

export const STROKE_ERROR_COLOR = '#F4212E'

export const STROKE_BACKGROUND_COLOR = '#38444D'

export const SUCCESS_CHARACTERS_LENGTH = 260

export const MAX_CHARACTERS_LENGTH = 280

export const START_STROKE_DASH_ARRAY = 56.5487

export const END_STROKE_DASH_ARRAY = 111

export const TOTAL_STROKE_DASH_ARRAY_DURATION =
  END_STROKE_DASH_ARRAY - START_STROKE_DASH_ARRAY

export const INCREMENTAL_STROKE_VALUE_PER_CHARACTER =
  TOTAL_STROKE_DASH_ARRAY_DURATION / MAX_CHARACTERS_LENGTH
